---
on: push
jobs:
  run-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deck
        uses: kong/setup-deck@v1
        with:
          deck-version: 1.8.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Deck
        run: deck sync --kong-addr http://0.0.0.0:8001
